# Generated by Django 3.1.1 on 2020-09-01 21:05

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("address", "0003_auto_20200830_1851"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=address.models.AddressField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="address.address",
            ),
            preserve_default=False,
        ),
    ]
