# Generated by Django 3.1.1 on 2020-09-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_date_added"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="product",
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(to="store.ProductImage"),
        ),
    ]
