# Generated by Django 3.1.1 on 2020-09-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cartitem_in_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='in_order',
            field=models.BooleanField(default=False),
        ),
    ]
